package com.ullink.slack.simpleslackapi.events;

public enum SlackEventType
{
    SLACK_CHANNEL_RENAMED,
    SLACK_CHANNEL_JOINED,
    SLACK_CHANNEL_LEFT,
    SLACK_GROUP_RENAMED,
    SLACK_GROUP_JOINED,
    SLACK_GROUP_LEFT,
    SLACK_MESSAGE_DELETED,
    SLACK_MESSAGE_UPDATED,
    SLACK_MESSAGE_POSTED,
    SLACK_IM_OPEN,
    SLACK_IM_CLOSE,
    SLACK_REPLY,
    SLACK_CONNECTED,
    UNKNOWN;
}
